//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionVecinal.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionVecinal.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        internal static string Errors_Compare {
            get {
                return ResourceManager.GetString("Errors_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo debe ser un correo electrónico válido.
        /// </summary>
        internal static string Errors_Email {
            get {
                return ResourceManager.GetString("Errors_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos.
        /// </summary>
        internal static string Errors_Login {
            get {
                return ResourceManager.GetString("Errors_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo debe tener como máximo {0} caracteres.
        /// </summary>
        internal static string Errors_MaxLength {
            get {
                return ResourceManager.GetString("Errors_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo debe tener al menos {0} caracteres.
        /// </summary>
        internal static string Errors_MinLength {
            get {
                return ResourceManager.GetString("Errors_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo debe tener al menos 8 caracteres, una letra mayúscula, una letra minúscula, un número y un carácter especial.
        /// </summary>
        internal static string Errors_Password {
            get {
                return ResourceManager.GetString("Errors_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este campo es requerido.
        /// </summary>
        internal static string Errors_Required {
            get {
                return ResourceManager.GetString("Errors_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        internal static string Labels_Login {
            get {
                return ResourceManager.GetString("Labels_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        internal static string Labels_Logout {
            get {
                return ResourceManager.GetString("Labels_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cierre primero la ventana \&quot;Añadir comunidad\&quot; para interactuar con esta ventana.
        /// </summary>
        internal static string Labels_OpenedNewCommunityWindow {
            get {
                return ResourceManager.GetString("Labels_OpenedNewCommunityWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string Labels_Password {
            get {
                return ResourceManager.GetString("Labels_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string Labels_Username {
            get {
                return ResourceManager.GetString("Labels_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenid@ a Gestión Vecinal.
        /// </summary>
        internal static string Labels_Welcome {
            get {
                return ResourceManager.GetString("Labels_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su contraseña.
        /// </summary>
        internal static string PlaceHolders_Password {
            get {
                return ResourceManager.GetString("PlaceHolders_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su usuario.
        /// </summary>
        internal static string PlaceHolders_Username {
            get {
                return ResourceManager.GetString("PlaceHolders_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de la comunidad.
        /// </summary>
        internal static string ViewComunidadLabels_Comunidad {
            get {
                return ResourceManager.GetString("ViewComunidadLabels_Comunidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Derramas.
        /// </summary>
        internal static string ViewComunidadLabels_Derramas {
            get {
                return ResourceManager.GetString("ViewComunidadLabels_Derramas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Facturas de proveedores.
        /// </summary>
        internal static string ViewComunidadLabels_Facturas {
            get {
                return ResourceManager.GetString("ViewComunidadLabels_Facturas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incidencias.
        /// </summary>
        internal static string ViewComunidadLabels_Incidencias {
            get {
                return ResourceManager.GetString("ViewComunidadLabels_Incidencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juntas.
        /// </summary>
        internal static string ViewComunidadLabels_Juntas {
            get {
                return ResourceManager.GetString("ViewComunidadLabels_Juntas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miembros de la comunidad.
        /// </summary>
        internal static string ViewComunidadLabels_Miembros {
            get {
                return ResourceManager.GetString("ViewComunidadLabels_Miembros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de presidencia.
        /// </summary>
        internal static string ViewComunidadLabels_Presidentes {
            get {
                return ResourceManager.GetString("ViewComunidadLabels_Presidentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedores.
        /// </summary>
        internal static string ViewComunidadLabels_Proveedores {
            get {
                return ResourceManager.GetString("ViewComunidadLabels_Proveedores", resourceCulture);
            }
        }
    }
}
